"""Create all tables

Revision ID: beb35866b0a4
Revises: 03f3f92a540d
Create Date: 2023-11-25 13:48:52.159073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beb35866b0a4'
down_revision = '03f3f92a540d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
